### ISSUE TITLE
Unable to use RealESRGAN_x4plus_anime6B

### ISSUE THREAD

**Issue by MuZzzlen** [DarthAffe/StableDiffusion.NET#32]
LogLine("Creating image ..."); 
  IImage?  imageTemp = await Task.Run(() => _model?.TextToImage(Prompt, parameter)); // 文本生成图像
   if (_upscaleModel != null&&imageTemp!= null)
   {
       LogLine("Upscaling image ..."); 
       Image = await Task.Run(
           () =>
               _upscaleModel?.Upscale(
                   imageTemp,
                   ESRGANUpscaleFactor
               )
       );
   }
   else
   {
       Image = imageTemp;
   }
   
![image](https://github.com/user-attachments/assets/e55ddd6a-0e40-4f7b-b41c-df20d221d048)

After generating the image and then using ESRGAN, the program immediately crashes

**Comment by DarthAffe** [comment]
Thanks for reporting this. It should be fixed with https://github.com/DarthAffe/StableDiffusion.NET/releases/tag/3.1.1

**Comment by MuZzzlen** [comment]
> Thanks for reporting this. It should be fixed with https://github.com/DarthAffe/StableDiffusion.NET/releases/tag/3.1.1感谢您报告此事。它应该用https://github.com/DarthAffe/StableDiffusion.NET/releases/tag/3.1.1修复
Thank you for your contribution. I can use it now, but the  （int upscaleFactor） parameters are not working

**Comment by MuZzzlen** [comment]
> Thanks for reporting this. It should be fixed with https://github.com/DarthAffe/StableDiffusion.NET/releases/tag/3.1.1

Thank you for your contribution. I can use it now, but the （int upscaleFactor） parameters are not working

**Comment by MuZzzlen** [comment]
> Thanks for reporting this. It should be fixed with https://github.com/DarthAffe/StableDiffusion.NET/releases/tag/3.1.1


Is it because the model （RealESRGAN_x4plus_anime_6B）itself cannot change the scaling factor？

**Comment by DarthAffe** [comment]
Yes, it seems like the upscale-factor is currently not used in stable-diffusion.cpp. it always uses the factor reported by the ESRGAN model.

**Comment by MuZzzlen** [comment]
> Yes, it seems like the upscale-factor is currently not used in stable-diffusion.cpp. it always uses the factor reported by the ESRGAN model.是的，似乎 upscale-factor 目前没有在 stable-diffusion.cpp 中使用。它始终使用 ESRGAN 模型报告的因子。

I understand, thank you！
