### ISSUE TITLE
Unable to use lora

### ISSUE THREAD

**Issue by MuZzzlen** [DarthAffe/StableDiffusion.NET#37]
![image](https://github.com/user-attachments/assets/10895660-ae32-470e-b49d-363e72208134)
I added a reference to the Lora folder, but it crashes immediately once I use Lora
![image](https://github.com/user-attachments/assets/d477d1b5-be39-4886-bdbe-3284ecefd9a9)
![image](https://github.com/user-attachments/assets/5d301537-1b5e-42ae-89bd-2293e3de8e2f)
![image](https://github.com/user-attachments/assets/d038238e-838c-48a2-a81c-de39ce69f7e3)

**Comment by DarthAffe** [comment]
Hey, i'm pretty sure this is related to https://github.com/DarthAffe/StableDiffusion.NET/issues/36 and caused by the non-ascii-characters in the prompt. Does the same prompt work in the stable-diffusion.cpp example app?

**Comment by MuZzzlen** [comment]
> Hey, i'm pretty sure this is related to #36 and caused by the non-ascii-characters in the prompt. Does the same prompt work in the stable-diffusion.cpp example app?嘿，我很确定这与 #36 是由提示符中的非 ASCII 字符引起的。在 stable-diffusion.cpp 示例应用程序中是否有相同的提示？

It seems like I made a mistake with non ascii characters. I updated to 3.2 and now I can use Lora
